### ISSUE TITLE
[rpgbosses-3.0.]Crashing upon starting a world

### ISSUE THREAD

**Issue by Subthy** [TenerPVPs/RpgBosses#2]
By the looks of it the mod is causing a crash, when starting a new world.

Here is a crash report:
[crash-2023-04-06_20.32.24-server.txt](https://github.com/TenerPVPs/RpgBosses/files/11173230/crash-2023-04-06_20.32.24-server.txt)

Here is a latest log, where you can see a crash report at the bottom:
[latest.log](https://github.com/TenerPVPs/RpgBosses/files/11173237/latest.log)

**Comment by TenerPVPs** [comment]
okie gonna look

**Comment by TenerPVPs** [comment]
Seens fixed now
