### ISSUE TITLE
[1.16.5][4.1] Mod encountered an error during the common_setup event phase.

### ISSUE THREAD

**Issue by Subthy** [TenerPVPs/RpgBosses#3]
Hello there,

I updated mod to the newest version and when I start the game, I receive this "Example mod (rpgbosses) encountered an error during the common_setup event phase. com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 13 column 24 path $.bosses..abilities"

The config is empty btw, I thought it was that at start, but no.

Here is the log and debug:
[latest.log](https://github.com/TenerPVPs/RpgBosses/files/11365677/latest.log)
[debug.log](https://github.com/TenerPVPs/RpgBosses/files/11365684/debug.log)

P.S

Which config palet is the right one, as there are many in CurseForge page (The one in pastebin, the one in github named abilitiesexamples and in CurseForge too under  "How configure abilities?"), as it's little bit confusing, at least for me

**Comment by Subthy** [comment]
Well, I created a new instance on CurseForge with the mod.

I used this template that is in cursforge page:

"cursed_realm_remastered:maudit": {
"minions": {
"minecraft:pig": {
"spawnChance": 0.5
}
},
"abilities": {
"guardian": {
"useGeneralConfigs": true
},
"soulrecovery": {
"useGeneralConfigs": true
}
},

It's wrong and you get the error that I posted above, it should be this, cause there are some brackets missing

{
"minecraft:zombie": {
    "minions": {
    "minecraft:pig": {
    "spawnChance": 1.0
    }
    },
    "abilities": {
    "guardian": {
    "useGeneralConfigs": true
    },
    "soulrecovery": {
    "useGeneralConfigs": true
    }
    }
}
}

, but the config is not taking any effect to the game.

This is the config that I used in the game that is not taking any effect:

{
"minecraft:zombie": {
    "minions": {
    "minecraft:pig": {
    "spawnChance": 1.0,
    "maxMinions": 5,
    "amountToSpawn": 3,
    "cooldownToSpawn": 60000,
    "cooldownCheckTarget": 15000
    }
    },
    "abilities": {
    "guardian": {
    "useGeneralConfigs": false,
    "distanceFromSpawn": 10,
    "instaRegen": true,
    "cooldownRegen": 0.1,
    "regenPerCooldown": 0.2
    },
    "soulrecovery": {
    "useGeneralConfigs": false,
    "soulHealAmount": 1.0
    }
    }
}
}

I tried different variations of it and still nothing worked.

**Comment by TenerPVPs** [comment]
Gonna look

**Comment by TenerPVPs** [comment]
> Well, I created a new instance on CurseForge with the mod.
> 
> I used this template that is in cursforge page:
> 
> "cursed_realm_remastered:maudit": { "minions": { "minecraft:pig": { "spawnChance": 0.5 } }, "abilities": { "guardian": { "useGeneralConfigs": true }, "soulrecovery": { "useGeneralConfigs": true } },
> 
> It's wrong and you get the error that I posted above, it should be this, cause there are some brackets missing
> 
> { "minecraft:zombie": { "minions": { "minecraft:pig": { "spawnChance": 1.0 } }, "abilities": { "guardian": { "useGeneralConfigs": true }, "soulrecovery": { "useGeneralConfigs": true } } } }
> 
> , but the config is not taking any effect to the game.
> 
> This is the config that I used in the game that is not taking any effect:
> 
> { "minecraft:zombie": { "minions": { "minecraft:pig": { "spawnChance": 1.0, "maxMinions": 5, "amountToSpawn": 3, "cooldownToSpawn": 60000, "cooldownCheckTarget": 15000 } }, "abilities": { "guardian": { "useGeneralConfigs": false, "distanceFromSpawn": 10, "instaRegen": true, "cooldownRegen": 0.1, "regenPerCooldown": 0.2 }, "soulrecovery": { "useGeneralConfigs": false, "soulHealAmount": 1.0 } } } }
> 
> I tried different variations of it and still nothing worked.

Can you send me the Full json file?

**Comment by TenerPVPs** [comment]
Cause i saw some errors on that json

**Comment by Subthy** [comment]
This is the only json that I have left, as I didn't save the other versions of the configs that I did.

Here is a pastebin link, as I can't send the json file here for some reason: https://pastebin.com/gseVFpQj

**Comment by Subthy** [comment]
How's it going with progress?

Btw if you would be so nice, could you give me a config that effects 2 different mobs, that have more then 2 minion types and abilities for the newest version of the mod. Cause I tried giving new version a shot, but I still can't make it work?

**Comment by Subthy** [comment]
got it working

**Comment by Subthy** [comment]
{
    "bosses": {
      "minecraft:zombie": {
        "minions": {
          "minecraft:sheep": {
            "spawnChance": 0.5
          }
        },
        "abilities": {
        },
        "infernalmobs_abilites": "1UP Alchimist Berserk Gravity Lifesteal Poisonous Regen Wither Sprint ",
        "champions_rank": 4,
        "champions_abilites": ["Adaptable", "Arctic", "Paralyzing", "Molten"],
        "maxMinions": 5,
        "amountToSpawn": 3,
        "cooldownToSpawn": 60000,
        "cooldownCheckTarget": 15000,
        "undefeatableRank": 0
      },
      "minecraft:skeleton": {
        "minions": {
          "minecraft:pig": {
            "spawnChance": 0.5
          }
        },
        "abilities": {
        },
        "infernalmobs_abilites": "1UP Alchimist Berserk Gravity Lifesteal Poisonous Regen Wither Sprint ",
        "champions_rank": 4,
        "champions_abilites": ["Adaptable", "Arctic", "Paralyzing", "Molten"],
        "maxMinions": 5,
        "amountToSpawn": 3,
        "cooldownToSpawn": 60000,
        "cooldownCheckTarget": 15000,
        "undefeatableRank": 0
      }
    },
    "general": {
      "abilities": {}
    }
}
This config worked
